services:
  - type: web
    name: A Save Restricted Content Bot
    runtime: python
    buildCommand: "pip install -r requirements.txt && python3 bot.py"
    startCommand: "python3 main.py"
    envVars:
      - key: PORT
        value: 8080
      - key: PYTHON_VERSION
        value: 3.10.8
      - key: TG_BOT_TOKEN
        description: "8056263089:AAHMI88zp5GyHzeaQS82BKNzGFzEI_5DAPs"
      - key: APP_ID
        description: "25444644"
      - key: API_HASH
        description: "bff60a5f566d9a54c175b0001ba9615b""
       # Replace with your channel ID
      - key: DATABASE_URL
        description: "mongodb+srv://lelouchlightlevi:gZRinZeJNXI55Va0@cluster0.n99js.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      - key: ADMINS
        value: "5969730414"  # Replace with admin user IDs (space-separated)
